language: python
dist: trusty
sudo: required

services:
  - docker

before_install:
  - sudo apt-add-repository -y 'ppa:duggan/bats'
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty-backports universe'
  - sudo apt-get update -qq
  - sudo apt-get install -y bats shellcheck
  - sudo apt-get install -y -o Dpkg::Options::="--force-confold" docker-engine

script:
  - python setup.py develop
  - pip install coverage
  - docker version
  - docker-compose version
  - tests/utils/run_tests.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -X coveragepy

notifications:
  email: false
